[package]
name = "turing-drawings-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8"
image = { version = "0.25", default_features = false, features = ["png"] }

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
debug = 1
debug-assertions = false